"""Install the migrated corlinman jobs into hermes's native cron.

The installer does three things and refuses to do a fourth:

1. **Copies** ``scripts/corlinman_jobs_lib.py`` verbatim into
   ``$HERMES_HOME/scripts/`` — hermes only runs cron scripts that resolve
   inside that directory (``cron/scheduler.py::_run_job_script``).
2. **Generates** one small entry script per job that needs one: an import of
   that library plus a single call to the matching ``main_*`` with the job's
   parameter bag baked in as literals. The generated text is a pure function
   of :mod:`plugins.corlinman_jobs.specs`, so re-running the installer either
   produces byte-identical files or a diff someone asked for.
3. **Creates** each job through ``cron.jobs.create_job`` and immediately
   pauses it.

The fourth thing — enabling anything — is not implemented here at all. Every
spec carries ``install_enabled=False`` and :func:`install` asserts it; turning
a job on is a deliberate ``hermes cron resume <name>`` by a human who has read
``docs/migration-corlinman/D1-cron-port-notes.md``. Three of these jobs post
to a real public QQ feed that already holds 19 real posts, and there is no
delete tool on the far side.

Two design points worth stating up front:

**The create→pause window is not a race.** ``create_job`` has no "create
paused" mode, so a job exists enabled for the microseconds between the two
calls. It cannot fire in that window: ``compute_next_run`` sets
``next_run_at`` to the next *future* occurrence of the cron expression and
``get_due_jobs`` only returns jobs whose ``next_run_at`` has passed. The
earliest possible fire is minutes away; the pause lands first. If
``pause_job`` somehow fails, :func:`install` says so loudly and names the job
rather than reporting success.

**Nothing is overwritten silently.** Every file the installer writes is
recorded in ``$HERMES_HOME/plugin-data/corlinman_jobs/install-manifest.json``
with its SHA-256. On the next run a file whose on-disk hash still matches the
recorded one is ours to refresh; a file that has drifted from both the plan
and the manifest is treated as hand-edited, reported as a ``conflict``, and
aborts the install before a single byte is written. ``--force`` overrides,
loudly.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

from . import preflight
from .preflight import Check
from .specs import JOB_SPECS, PERSONA_ID, JobSpec

#: The shared job-side library, copied verbatim.
LIB_FILENAME = "corlinman_jobs_lib.py"

#: Bookkeeping for "did we write this file, or did a human edit it".
MANIFEST_FILENAME = "install-manifest.json"
MANIFEST_VERSION = 1

#: Present in every generated entry script; makes the provenance greppable
#: on a host where nobody remembers what created these files.
GENERATED_MARKER = "generated by plugins.corlinman_jobs.installer"

#: hermes has no "no toolsets" spelling for a cron job. An empty
#: ``enabled_toolsets`` list is falsy, so ``_resolve_cron_enabled_toolsets``
#: skips it and falls back to the ``cron`` platform's configured toolsets —
#: i.e. an empty allowlist quietly means *more* tools, not fewer. The
#: ``no_mcp`` sentinel is the one value that survives to the agent as a
#: genuinely empty list: ``_merge_mcp_into_per_job_toolsets`` strips it and
#: returns ``[]``, and ``model_tools.get_tool_definitions`` treats ``[]``
#: (not None) as "include nothing". This is how ``hermes.diary_summary``
#: reproduces the source's ``tools_enabled=False``.
NO_TOOLS_SENTINEL = "no_mcp"

#: ``hermes.diary_summary``'s channel filter. The source hardcoded this list
#: in ``_diary_summary_action`` instead of reading it from the job metadata
#: (unlike ``_analysis_digest_action``, which takes ``metadata["channels"]``),
#: so it is not in the spec's verbatim parameter bag and is restated here.
#: specs.py holds what corlinman stored; the installer holds what corlinman
#: *did*.
DIARY_CHANNELS: tuple[str, ...] = ("telegram", "gateway")

#: Job fields the installer compares when an install finds a job already
#: present, so "already installed" can distinguish "identical" from "someone
#: changed it".
_COMPARED_JOB_FIELDS = (
    "schedule_display",
    "script",
    "no_agent",
    "deliver",
    "prompt",
    "enabled_toolsets",
)


# ---------------------------------------------------------------------------
# Locations
# ---------------------------------------------------------------------------


def repo_root() -> Path:
    """The hermes checkout holding this plugin."""
    return Path(__file__).resolve().parents[2]


def source_lib_path() -> Path:
    """In-tree copy of the job-side library — the thing that gets copied."""
    return Path(__file__).resolve().parent / "scripts" / LIB_FILENAME


def hermes_home() -> Path:
    """The active profile home, resolved fresh on every call.

    Deliberately not cached: tests and embedders re-point ``HERMES_HOME``
    after import, and a cached value here would write the generated scripts
    into whichever profile happened to be active when the module loaded.
    """
    from hermes_constants import get_hermes_home

    return Path(get_hermes_home())


def scripts_dir() -> Path:
    """``$HERMES_HOME/scripts`` — the only directory cron will run from."""
    return hermes_home() / "scripts"


def state_dir() -> Path:
    """Where the install manifest lives. Same directory the jobs use."""
    return hermes_home() / "plugin-data" / "corlinman_jobs"


def manifest_path() -> Path:
    return state_dir() / MANIFEST_FILENAME


def grantley_decay_script() -> Path:
    """Absolute path to ``grantley_job.py``, deployed copy preferred.

    ``persona.decay`` runs plugins/grantley's decay in place rather than
    copying it: that script resolves its package by walking up from its own
    ``__file__``, so a copy in ``$HERMES_HOME/scripts/`` would import
    nothing. The deployed copy under ``$HERMES_HOME/plugins/grantley/`` is
    preferred because that is the one ``plugins/memory`` actually loads as
    the memory provider — running decay against the repo copy while the
    provider serves the deployed one would decay a different database.
    """
    deployed = hermes_home() / "plugins" / "grantley" / "scripts" / "grantley_job.py"
    if deployed.is_file():
        return deployed
    return repo_root() / "plugins" / "grantley" / "scripts" / "grantley_job.py"


# ---------------------------------------------------------------------------
# Generated entry scripts
# ---------------------------------------------------------------------------


def script_call(spec: JobSpec) -> tuple[str, dict[str, Any], bool]:
    """``(function name, keyword arguments, silence stdout)`` for one job.

    This is the single place the verbatim corlinman parameter bag in
    :mod:`~plugins.corlinman_jobs.specs` is translated into a call into
    :mod:`corlinman_jobs_lib`. Keeping it in one function means a parameter
    can only be misread once.

    Raises ``KeyError`` for a job that declares a ``script`` this table does
    not know about — better than generating a script that fails at 07:07.
    """
    params: Mapping[str, Any] = spec.params

    if spec.name == "hermes.daily_agenda":
        return (
            "main_daily_agenda",
            {
                "agenda_path": str(params["agenda_path"]),
                "timezone": spec.timezone,
            },
            False,
        )
    if spec.name == "hermes.analysis_digest":
        return (
            "main_analysis_material",
            {
                "user_id": str(params["user_id"]),
                "channels": [str(c) for c in params["channels"]],
                "timezone": spec.timezone,
            },
            False,
        )
    if spec.name == "hermes.diary_summary":
        return (
            "main_diary_material",
            {
                "user_id": str(params["user_id"]),
                # Not from params — see DIARY_CHANNELS.
                "channels": list(DIARY_CHANNELS),
                "timezone": spec.timezone,
            },
            False,
        )
    if spec.name == "hermes.youtube_daily":
        return (
            "main_youtube_state",
            {
                "job_name": spec.name,
                "channels": [str(c) for c in params["youtube_channels"]],
                "state_file": str(params["state_file"]),
            },
            False,
        )
    if spec.name == "hermes.qzone_daily":
        return (
            "main_qzone_recent_posts",
            {
                # The cron subprocess environment strips hermes-owned
                # PYTHONPATH entries (tools/environments/local.py::
                # _strip_hermes_owned_pythonpath), so the repository root has
                # to be handed over explicitly for `import plugins.qzone`.
                "repo_root": str(repo_root()),
                "persona_id": str(params["persona_id"]),
            },
            False,
        )
    if spec.name == "persona.decay":
        return (
            "main_grantley_decay",
            {
                "script_path": str(grantley_decay_script()),
                "persona_id": PERSONA_ID,
            },
            # grantley_job.py prints its result payload as JSON on stdout. For
            # a no_agent job stdout IS the delivered message, and an hourly
            # "{"ok": true, "rows_changed": 0}" is noise nobody asked for —
            # corlinman's decay delivered nothing. Routing it to stderr makes
            # the tick silent on success (hermes treats empty stdout as
            # "nothing to report") while a non-zero exit still fails the job
            # loudly and carries the payload into the error report.
            True,
        )
    raise KeyError(
        f"{spec.name} declares script={spec.script!r} but installer.script_call "
        "has no entry for it"
    )


def _py_literal(value: Any, indent: int = 4) -> str:
    """Render *value* as a deterministic Python literal.

    Deterministic because drift detection compares bytes: the same spec must
    always render to the same file, or every install would report a conflict.
    """
    if value is None or isinstance(value, (bool, int, float, str)):
        return repr(value)
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        pad = " " * (indent + 4)
        body = "".join(f"{pad}{_py_literal(item, indent + 4)},\n" for item in value)
        return "[\n" + body + " " * indent + "]"
    raise TypeError(f"cannot bake {type(value).__name__} into a generated script")


def render_entry_script(spec: JobSpec) -> str:
    """The full text of one job's generated entry script."""
    function, kwargs, silent = script_call(spec)
    args = "".join(
        f"    {key}={_py_literal(kwargs[key])},\n" for key in sorted(kwargs)
    )
    header = (
        "#!/usr/bin/env python3\n"
        f'"""{spec.name} — {GENERATED_MARKER}.\n'
        "\n"
        "Do not edit. Re-run `hermes corlinman-jobs install` to regenerate;\n"
        "local edits are detected and refused rather than overwritten.\n"
        f'"""\n\n'
    )
    if not silent:
        return (
            header
            + f"from {LIB_FILENAME[:-3]} import {function}\n"
            "\n"
            f"raise SystemExit({function}(\n{args}))\n"
        )
    return (
        header
        + "import contextlib\n"
        "import sys\n"
        "\n"
        f"from {LIB_FILENAME[:-3]} import {function}\n"
        "\n"
        "with contextlib.redirect_stdout(sys.stderr):\n"
        f"    _code = {function}(\n{args}    )\n"
        "raise SystemExit(_code)\n"
    )


def planned_files(specs: Sequence[JobSpec] = JOB_SPECS) -> dict[str, str]:
    """``filename -> content`` for everything the install would write.

    The library comes first so a reader of the plan sees the dependency
    before its dependents.
    """
    files: dict[str, str] = {}
    scripted = [spec for spec in specs if spec.script]
    if scripted:
        files[LIB_FILENAME] = source_lib_path().read_text(encoding="utf-8")
    for spec in scripted:
        files[str(spec.script)] = render_entry_script(spec)
    return files


# ---------------------------------------------------------------------------
# Drift detection
# ---------------------------------------------------------------------------


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read_manifest() -> dict:
    """The last install's record, or an empty one. Never raises."""
    try:
        raw = json.loads(manifest_path().read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return raw if isinstance(raw, dict) else {}


def _recorded_hashes() -> dict[str, str]:
    files = read_manifest().get("files")
    if not isinstance(files, dict):
        return {}
    return {str(k): str(v) for k, v in files.items()}


@dataclass(frozen=True)
class FileAction:
    """What the install would do to one file in ``$HERMES_HOME/scripts/``."""

    filename: str
    path: Path
    #: ``create`` | ``update`` | ``unchanged`` | ``conflict``
    action: str
    reason: str

    @property
    def blocking(self) -> bool:
        return self.action == "conflict"


def file_actions(specs: Sequence[JobSpec] = JOB_SPECS) -> tuple[FileAction, ...]:
    """Classify every planned file against what is on disk. Read-only."""
    recorded = _recorded_hashes()
    directory = scripts_dir()
    out: list[FileAction] = []
    for filename, content in planned_files(specs).items():
        target = directory / filename
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError:
            out.append(
                FileAction(filename, target, "create", "not present in this profile")
            )
            continue
        if existing == content:
            out.append(FileAction(filename, target, "unchanged", "already current"))
            continue
        existing_hash = _sha256(existing)
        if recorded.get(filename) == existing_hash:
            out.append(
                FileAction(
                    filename,
                    target,
                    "update",
                    "installed by a previous run; the repository copy has changed",
                )
            )
            continue
        out.append(
            FileAction(
                filename,
                target,
                "conflict",
                "on disk but not written by this installer (hand-edited, or "
                "installed before the manifest existed) — inspect it, then "
                "re-run with --force to overwrite",
            )
        )
    return tuple(out)


def script_drift(specs: Sequence[JobSpec] = JOB_SPECS) -> dict[str, str]:
    """``filename -> "ok" | "missing" | "stale"``.

    The vocabulary preflight's ``check_scripts_installed`` speaks. A
    ``conflict`` reports as ``stale`` there — from the *enable* gate's point
    of view a hand-edited script and an outdated one are the same hazard,
    "the file running at 22:21 is not the file that was reviewed". The
    installer keeps the finer distinction; see :func:`file_actions`.
    """
    mapping = {
        "create": "missing",
        "update": "stale",
        "conflict": "stale",
        "unchanged": "ok",
    }
    return {action.filename: mapping[action.action] for action in file_actions(specs)}


# ---------------------------------------------------------------------------
# Job planning
# ---------------------------------------------------------------------------


def _existing_jobs() -> dict[str, dict]:
    from cron.jobs import load_jobs

    out: dict[str, dict] = {}
    for job in load_jobs():
        if isinstance(job, dict) and job.get("name"):
            out[str(job["name"])] = job
    return out


def _spec_job_fields(spec: JobSpec) -> dict[str, Any]:
    """The ``create_job`` keyword arguments this spec implies."""
    toolsets: Optional[list[str]]
    if spec.no_agent:
        toolsets = None
    elif spec.enabled_toolsets is None:
        toolsets = None
    elif len(spec.enabled_toolsets) == 0:
        toolsets = [NO_TOOLS_SENTINEL]
    else:
        toolsets = list(spec.enabled_toolsets)
    return {
        "prompt": spec.prompt,
        "schedule": spec.schedule,
        "name": spec.name,
        "deliver": spec.deliver,
        "script": spec.script,
        "no_agent": spec.no_agent,
        "enabled_toolsets": toolsets,
    }


def _job_differences(spec: JobSpec, job: Mapping[str, Any]) -> list[str]:
    """Fields where an already-installed job disagrees with its spec."""
    fields = _spec_job_fields(spec)
    want = {
        "schedule_display": spec.schedule,
        "script": fields["script"],
        "no_agent": fields["no_agent"],
        "deliver": fields["deliver"],
        "prompt": fields["prompt"] or "",
        "enabled_toolsets": fields["enabled_toolsets"],
    }
    out = []
    for key in _COMPARED_JOB_FIELDS:
        have = job.get(key)
        if key == "enabled_toolsets":
            have = list(have) if have else None
        if have != want[key]:
            out.append(key)
    return out


@dataclass(frozen=True)
class JobAction:
    """What the install would do to one cron job."""

    name: str
    #: ``create`` | ``exists``
    action: str
    reason: str
    spec: JobSpec


def job_actions(specs: Sequence[JobSpec] = JOB_SPECS) -> tuple[JobAction, ...]:
    """Classify every spec against the cron store. Read-only."""
    existing = _existing_jobs()
    out: list[JobAction] = []
    for spec in specs:
        job = existing.get(spec.name)
        if job is None:
            out.append(
                JobAction(spec.name, "create", "not present; will be created paused", spec)
            )
            continue
        state = "paused" if not job.get("enabled") else "ENABLED"
        differences = _job_differences(spec, job)
        detail = f"already installed as {job.get('id')} ({state})"
        if differences:
            detail += "; differs from the spec in " + ", ".join(differences)
        detail += ". Left untouched — remove it first if you want it rebuilt"
        out.append(JobAction(spec.name, "exists", detail, spec))
    return tuple(out)


# ---------------------------------------------------------------------------
# The plan
# ---------------------------------------------------------------------------


def needs_qq(spec: JobSpec) -> bool:
    """Whether this job talks to QQ, and so needs the QQ preflight checks."""
    return "onebot" in (spec.enabled_toolsets or ())


def select_specs(only: Optional[Sequence[str]] = None) -> tuple[JobSpec, ...]:
    """Resolve a ``--only`` selection to specs, rejecting unknown names."""
    if not only:
        return JOB_SPECS
    wanted = list(only)
    known = {spec.name: spec for spec in JOB_SPECS}
    missing = [name for name in wanted if name not in known]
    if missing:
        raise KeyError(
            f"unknown job(s): {', '.join(missing)}; known: {', '.join(sorted(known))}"
        )
    return tuple(spec for spec in JOB_SPECS if spec.name in set(wanted))


@dataclass(frozen=True)
class Plan:
    """Everything an install would do, computed without doing any of it."""

    specs: tuple[JobSpec, ...]
    files: tuple[FileAction, ...]
    jobs: tuple[JobAction, ...]
    checks: tuple[Check, ...]
    scripts_dir: Path

    @property
    def blocking_checks(self) -> tuple[Check, ...]:
        return tuple(check for check in self.checks if check.blocking)

    @property
    def conflicts(self) -> tuple[FileAction, ...]:
        return tuple(action for action in self.files if action.blocking)

    @property
    def blocked(self) -> bool:
        return bool(self.blocking_checks or self.conflicts)

    @property
    def would_write(self) -> tuple[FileAction, ...]:
        return tuple(a for a in self.files if a.action in {"create", "update", "conflict"})

    @property
    def would_create(self) -> tuple[JobAction, ...]:
        return tuple(a for a in self.jobs if a.action == "create")


def plan(only: Optional[Sequence[str]] = None) -> Plan:
    """Compute the install plan. **No side effects of any kind.**

    Not one byte is written, no directory is created, no job is touched and
    no model, QQ session or Telegram API is contacted. The preflight checks
    read configuration and the qzone ledgers; that is the extent of it.

    ``include_scripts=False`` on the preflight run is deliberate: the script
    check exists to gate *enabling* a job, and asking it before an install
    would fail every fresh profile for not yet having the files this install
    is about to write.
    """
    specs = select_specs(only)
    checks = preflight.run_checks(
        include_qq=any(needs_qq(spec) for spec in specs),
        include_scripts=False,
    )
    return Plan(
        specs=specs,
        files=file_actions(specs),
        jobs=job_actions(specs),
        checks=tuple(checks),
        scripts_dir=scripts_dir(),
    )


def format_plan(plan_obj: Plan) -> str:
    """Render a plan for a terminal. Pure formatting."""
    lines: list[str] = []
    lines.append(f"corlinman → hermes cron install plan ({len(plan_obj.specs)} job(s))")
    lines.append(f"  profile scripts dir: {plan_obj.scripts_dir}")
    lines.append("")

    lines.append("preflight")
    for check in plan_obj.checks:
        mark = {preflight.OK: "ok  ", preflight.WARN: "warn", preflight.FAIL: "FAIL"}[
            check.level
        ]
        lines.append(f"  [{mark}] {check.key}: {check.message}")
        if check.detail:
            lines.append(f"         {check.detail}")
    lines.append("")

    lines.append("files")
    if not plan_obj.files:
        lines.append("  (none — the selected jobs need no scripts)")
    for action in plan_obj.files:
        lines.append(f"  {action.action:<9} {action.filename} — {action.reason}")
    lines.append("")

    lines.append("jobs")
    for action in plan_obj.jobs:
        spec = action.spec
        mode = "no_agent script" if spec.no_agent else "agent"
        lines.append(
            f"  {action.action:<9} {spec.name}  [{spec.schedule}]  {mode}  "
            f"→ {spec.deliver}"
        )
        lines.append(f"            {action.reason}")
        if action.action == "create":
            lines.append(f"            paused on creation: {spec.disabled_reason}")
            if spec.writes_public_feed:
                lines.append(
                    "            WRITES A REAL PUBLIC QQ FEED when enabled — "
                    "no undo exists"
                )
    lines.append("")

    if plan_obj.blocked:
        lines.append("BLOCKED — nothing would be installed:")
        for check in plan_obj.blocking_checks:
            lines.append(f"  preflight {check.key}: {check.message}")
        for action in plan_obj.conflicts:
            lines.append(f"  file {action.filename}: {action.reason}")
    else:
        lines.append(
            f"ready: {len(plan_obj.would_write)} file(s) to write, "
            f"{len(plan_obj.would_create)} job(s) to create (all paused)"
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# The install
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InstallResult:
    """Outcome of a real install."""

    plan: Plan
    ok: bool
    error: str = ""
    written: tuple[str, ...] = ()
    created: tuple[tuple[str, str], ...] = ()
    skipped: tuple[str, ...] = ()
    #: Jobs that were created but could not be paused. Non-empty means a job
    #: is live that should not be; the caller must treat this as an incident.
    unpaused: tuple[str, ...] = ()


def install(
    only: Optional[Sequence[str]] = None,
    *,
    force: bool = False,
) -> InstallResult:
    """Write the scripts and create the jobs, paused.

    Aborts before writing anything when preflight reports a ``FAIL`` or when
    a file on disk was not written by this installer. ``force=True`` waives
    only the second of those — a failing preflight is never waivable, because
    every one of those checks guards against a silently wrong result (a
    schedule an hour off, a dedup ledger read from the wrong path) rather
    than an error somebody would notice.
    """
    current = plan(only)

    if current.blocking_checks:
        return InstallResult(
            plan=current,
            ok=False,
            error="preflight failed: "
            + "; ".join(f"{c.key}: {c.message}" for c in current.blocking_checks),
        )
    if current.conflicts and not force:
        return InstallResult(
            plan=current,
            ok=False,
            error="local edits would be overwritten: "
            + ", ".join(a.filename for a in current.conflicts)
            + " (re-run with --force to overwrite)",
        )

    for spec in current.specs:
        # A belt-and-braces read of the invariant the whole migration rests
        # on. If a spec ever grows install_enabled=True, stop here rather
        # than discovering it when a QQ post appears.
        if spec.install_enabled:
            return InstallResult(
                plan=current,
                ok=False,
                error=f"{spec.name} has install_enabled=True; refusing to install "
                "a job the migration is not allowed to enable",
            )

    directory = scripts_dir()
    directory.mkdir(parents=True, exist_ok=True)
    contents = planned_files(current.specs)
    written: list[str] = []
    hashes = _recorded_hashes()
    for action in current.files:
        if action.action == "unchanged":
            hashes[action.filename] = _sha256(contents[action.filename])
            continue
        text = contents[action.filename]
        action.path.write_text(text, encoding="utf-8")
        hashes[action.filename] = _sha256(text)
        written.append(action.filename)

    from cron.jobs import create_job, pause_job

    created: list[tuple[str, str]] = []
    skipped: list[str] = []
    unpaused: list[str] = []
    for job_action in current.jobs:
        if job_action.action != "create":
            skipped.append(job_action.name)
            continue
        spec = job_action.spec
        job = create_job(**_spec_job_fields(spec))
        paused = pause_job(job["id"], reason=spec.disabled_reason)
        if paused is None or paused.get("enabled"):
            unpaused.append(spec.name)
        created.append((spec.name, str(job["id"])))

    _write_manifest(hashes, created)

    return InstallResult(
        plan=current,
        ok=not unpaused,
        error=(
            "created but NOT paused: " + ", ".join(unpaused) + " — pause them by hand now"
            if unpaused
            else ""
        ),
        written=tuple(written),
        created=tuple(created),
        skipped=tuple(skipped),
        unpaused=tuple(unpaused),
    )


def _write_manifest(hashes: Mapping[str, str], created: Sequence[tuple[str, str]]) -> None:
    """Record what we wrote, so the next run can tell our files from edits."""
    previous = read_manifest()
    jobs = previous.get("jobs")
    jobs = dict(jobs) if isinstance(jobs, dict) else {}
    jobs.update({name: job_id for name, job_id in created})
    payload = {
        "version": MANIFEST_VERSION,
        "repo_root": str(repo_root()),
        "files": dict(sorted(hashes.items())),
        "jobs": dict(sorted(jobs.items())),
    }
    path = manifest_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".new")
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.replace(path)


def status(only: Optional[Sequence[str]] = None) -> str:
    """Post-install readiness report, including the enable-time script check."""
    specs = select_specs(only)
    checks = preflight.run_checks(
        include_qq=any(needs_qq(spec) for spec in specs),
        include_scripts=True,
    )
    existing = _existing_jobs()
    lines = ["corlinman job status", ""]
    for check in checks:
        mark = {preflight.OK: "ok  ", preflight.WARN: "warn", preflight.FAIL: "FAIL"}[
            check.level
        ]
        lines.append(f"  [{mark}] {check.key}: {check.message}")
    lines.append("")
    for spec in specs:
        job = existing.get(spec.name)
        if job is None:
            lines.append(f"  {spec.name}: NOT INSTALLED")
            continue
        state = "paused" if not job.get("enabled") else "ENABLED"
        lines.append(
            f"  {spec.name}: {state}  id={job.get('id')}  "
            f"next={job.get('next_run_at')}  last={job.get('last_status')}"
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI — `hermes corlinman-jobs {plan,install,status}`
# ---------------------------------------------------------------------------


def register_cli(subparser: argparse.ArgumentParser) -> None:
    """Wire the subcommands. Called by the plugin loader through register()."""
    subs = subparser.add_subparsers(dest="corlinman_jobs_action")

    plan_p = subs.add_parser(
        "plan", help="Show what an install would do. Writes nothing."
    )
    plan_p.add_argument("--only", action="append", default=None, metavar="JOB")

    install_p = subs.add_parser(
        "install", help="Install the jobs (created paused) and their scripts"
    )
    install_p.add_argument("--only", action="append", default=None, metavar="JOB")
    install_p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite scripts this installer did not write (never waives preflight)",
    )

    status_p = subs.add_parser("status", help="Installed / paused / preflight report")
    status_p.add_argument("--only", action="append", default=None, metavar="JOB")


def corlinman_jobs_command(args: argparse.Namespace) -> int:
    """Dispatch. Returns a process exit code."""
    action = getattr(args, "corlinman_jobs_action", None)
    if not action:
        print("Usage: hermes corlinman-jobs {plan|install|status}")
        return 2
    only = getattr(args, "only", None)
    try:
        if action == "plan":
            current = plan(only)
            print(format_plan(current))
            return 1 if current.blocked else 0
        if action == "status":
            print(status(only))
            return 0
        if action == "install":
            result = install(only, force=bool(getattr(args, "force", False)))
            print(format_plan(result.plan))
            print("")
            if not result.ok:
                print(f"install failed: {result.error}", file=sys.stderr)
                return 1
            print(f"wrote {len(result.written)} file(s): {', '.join(result.written) or '-'}")
            for name, job_id in result.created:
                print(f"created (paused) {name} → {job_id}")
            for name in result.skipped:
                print(f"skipped {name} (already installed)")
            print(
                "\nEvery job is PAUSED. Enable one only after reading "
                "docs/migration-corlinman/D1-cron-port-notes.md:\n"
                "    hermes cron resume <name>"
            )
            return 0
    except KeyError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"unknown action {action!r}", file=sys.stderr)
    return 2


__all__ = [
    "DIARY_CHANNELS",
    "GENERATED_MARKER",
    "LIB_FILENAME",
    "MANIFEST_FILENAME",
    "NO_TOOLS_SENTINEL",
    "FileAction",
    "InstallResult",
    "JobAction",
    "Plan",
    "corlinman_jobs_command",
    "file_actions",
    "format_plan",
    "grantley_decay_script",
    "hermes_home",
    "install",
    "job_actions",
    "manifest_path",
    "needs_qq",
    "plan",
    "planned_files",
    "read_manifest",
    "register_cli",
    "render_entry_script",
    "repo_root",
    "script_call",
    "script_drift",
    "scripts_dir",
    "select_specs",
    "source_lib_path",
    "state_dir",
    "status",
]
